### ISSUE TITLE
Does it support Shell and Shell Navigation?

### ISSUE THREAD

**Issue by JamestsaiTW** [Redth/Maui.UITesting#23]
I try this project to the default mauiapp template by Visual Studio 2022 (v17.4.1).

I set the button of "MainPage.xaml" and its' AutomationId is "CounterBtn". 

UITest code is:
~~~C#
await driver.AutomationId("CounterBtn").Tap();
~~~

When I set 
~~~C#
MainPage = new MainPage(); 
~~~
at App.xaml.cs, it can work will.

But when I set
~~~C#
MainPage = new AppShell();
~~~
at App.xaml.cs and AppShell.xaml is:
~~~XML
<Shell
    x:Class="MauiApp2.AppShell"
    xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:local="clr-namespace:MauiApp2"
    Shell.FlyoutBehavior="Disabled">
    <ShellContent
        Title="Home"
        ContentTemplate="{DataTemplate local:MainPage}"
        Route="MainPage" />
</Shell>
~~~
 it can't work and I got the following error messages:
~~~
Error: Microsoft.Maui.Automation.ElementsNotFoundException: Elements not found matching query
   at Microsoft.Maui.Automation.Querying.DriverQuery.AutoWait(Int32 autoWaitMs, Int32 retryDelayMs, Boolean waitForNone)
   at Submission#9.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)
~~~

If it supports Shell and Shell navigation, how should I do for my UITest code?

**Comment by momo44633** [comment]
hello, did you find a solution? i'm stuck with the same issue

**Comment by JamestsaiTW** [comment]
No, I still stuck it.🥲

**Comment by mdelgadov** [comment]
Allow my two cents: I don't think it's a problem with this software. When the test starts, there is no app and thus, no page is loaded, no shell loaded in the window and no real maui context.
I'm trying to create a mock app with a mock shell, pretty much Redth does it in this tests.

I've been hitting my poor head against this wall for two months, but if I can create a mock app with a mock shell. Current, I'm golden.

Also, I wouldn't feel compelled to test the navigation per se, if there is a page and a route, that is pretty much guaranteed, or a much bigger problem is occurring.
